#!/usr/bin/python3
import websockcontrol
import argparse
from time import sleep
def main():

    args = get_args()

    ws = websockcontrol
    
    wsc = ws.WebsocketClearone(args.settings)
    wsc.connect_clearone()
    commands = load_commands(args.commands)
    for command in commands:
        print(command)
        print(wsc.clearone_device.send_command(command))
        sleep(.05)
    
def load_commands(file):  
    try:
        with open(file) as fh:
            commands = fh.read().splitlines()
    except Exception as e:
        raise Exception(
                'An error occured trying to open settings file: %s, %s'
                % (file, e)
                )
    return commands
    
def get_args():
    parser = argparse.ArgumentParser(
        description="Clearone Midi Control",
        formatter_class=argparse.RawTextHelpFormatter
    )
    required_argument = parser.add_argument_group("required arguments")
    required_argument.add_argument(
        "-s", 
        "--settings",
        help="Settings JSON file",
        required=True
    )
    required_argument.add_argument(
        "-c", 
        "--commands",
        help="Command file, commands line by line in a file",
        required=True
    )
    
    return(parser.parse_args())
    
if __name__ == "__main__":
    main()